spring.application.name=vintage-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/vintage
spring.datasource.username=simahyeon
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update